### ISSUE TITLE
Error loading stylers.xml

### ISSUE THREAD

**Issue by dixonge** [naderi/material-theme-for-npp#1]
this fails when attempting to change to your theme/style in the Style Configurator...

**Comment by chrisonline** [comment]
Same to me. Any fix out there?

**Comment by naderi** [comment]
You should select the theme after importing it. 
Setting -> Style configurator... -> Select theme (combo box)

**Comment by toddnguyen47** [comment]
You need to install the Monaco font. You can simply google "Monaco font" and install the Monaco.ttf file.

**Comment by toddnguyen47** [comment]
Either that or open up the Material-Dark.xml file (using Notepad or Notepad++), Ctrl+f for "Monaco" and change that to any font you wish (Consolas, for example).

**Comment by danfournier** [comment]
Also, make sure you download the RAW XML file and not Github's HTML XML display page.
