### ISSUE TITLE
Does not work in Notepad++ 7.7 32bit

### ISSUE THREAD

**Issue by tekiegirl** [naderi/material-theme-for-npp#11]
Does not work in Notepad++ 7.7 32bit, although looking at the dates of other issues I am assuming that this theme is not being actively developed. A pity as it is nice.

**Comment by Biokore** [comment]
Just as said in a former note. Download the whole project and not only the XML. You'll see that the XML from the *.zip isn't the same size as the one downloaded with right click. 
I had the same issue, and this solved it. 

It runs on v7.7.1 x64 for Window 10

May be the issue remains for the x32 version ?

**Comment by tekiegirl** [comment]
Thanks, all sorted 😄
