### ISSUE TITLE
Errors out on select then crashes np++

### ISSUE THREAD

**Issue by SemperFu** [naderi/material-theme-for-npp#3]
C:\Users\s\AppData\Roaming\Notepad++\themes\Material-Dark.xml

Load stylers.xml failed!

**Comment by Ernestxp** [comment]
I have the portable version, and I import, then when I go to select the theme get the same message and crash: Load stylers.xml failed!

**Comment by frederikvanhoyweghen** [comment]
Bump, same issue

**Comment by naderi** [comment]
For people having issues with the installation process, I'd like to elaborate on what @sjpalf has already explained.

1. Open Run (Windows+R)
2. Go to %APPDATA%\Notepad++
3. Open themes folder, create a new folder named themes if it doesn't exist
4. Place downloaded .xml file inside the folder
5. Restart Notepad++
6. Open Settings->Style Configurator
7. Select Theme Name from the theme drop-down box.
8. Click Save & Close

As for the issue with the second method, yes the issues exists. But it is not specific to this particular theme.
