### ISSUE TITLE
Description Issue

### ISSUE THREAD

**Issue by arashtad** [naderi/material-theme-for-npp#4]
Could you please explain the installation process clearly?
The second method you provide doesn't work at all and the first method is completely confusing. What's the path to copy the XML file exactly?
There's not such directory on this PC.

**Comment by sjpalf** [comment]
For the first method, you use the %APPDATA% environment variable (in explorer, literally go to "%APPDATA%\Notepad++\themes\"), this most likely points to "c:\users\_username_\AppData\Roaming\Notepad++\themes\".
For the second method, it is likely that you've saved the html file from github by right-clicking on the filename and selecting save link as. If instead you click on the xml file then copy-paste the actual xml into a new file and save that as "%APPDATA%\Notepad++\themes\Material-Dark.xml" it should work

**Comment by Codextor** [comment]
For people having issues with the installation process, I'd like to elaborate on what @sjpalf has already explained.

1. Open **Run** (Windows+R)
2. Go to **%APPDATA%\Notepad++**
3. Open **themes** folder, create a new folder named **themes** if it doesn't exist
4. Place downloaded **.xml** file inside the folder
5. Restart Notepad++
6. Open *Settings->Style Configurator*
7. Select **Theme Name** from the theme drop-down box.
8. Click **Save & Close**

As for the issue with the second method, yes the issues exists. But it is not specific to this particular theme.
