### ISSUE TITLE
Does Not work for NOtepad++ v7.5.6

### ISSUE THREAD

**Issue by pgorbas** [naderi/material-theme-for-npp#5]
Does Not work for NOtepad++ v7.5.6.

I downloaded the file. and followed your install instructions.
```Installation:
Copy the Material-Dark.xml file to "%APPDATA%\Notepad++\themes" and in a portable installation to "%Notepad++%\themes".

Or simply import it to Notepad++ by going to Menu -> Settings -> Import -> Import Style theme(s) option.``

The appearance did not change.
I shut down and restarted NotePad++ - still no change.

**Comment by keithlockeaf** [comment]
Error from v7.5.4 64-bit:
I get the error "Load stylers.xml failed!" when I select the theme from the Style Configuration

**Comment by ChristopherVilla** [comment]
Which of the **three** methods did you use ?

**Comment by en-casa** [comment]
I fixed this by renaming the Material-Dark.xml to stylers.xml, and perhaps renaming the old one as "stylers old.xml" just to keep it around. then restart npp!

i found this file in "C:\Users\<username>\AppData\Roaming\Notepad++"

**Comment by edumelzer** [comment]
It's working on v7.5.6 to me. How did you downloaded the XML file? Using "right click" + "save as" on github doesn't work because it includes github's HTML code. I recommend you open file and verify if it's a valid XML.

**Comment by iexcept** [comment]
Not working on v7.5.7 (installed to Program Files, imported via menu)

**Comment by hemanthhyperface** [comment]
not working

**Comment by santidiaz** [comment]
not working on v7.7 also

**Comment by naderi** [comment]
As mentioned above, simply downloading the xml file via right click from GitHub doesn't work because the file downloaded this way is not a valid xml. You have to :

- download the whole project
- extract the xml file and copy it in C:\Users<YourUser>AppData\Roaming\Notepad++\themes\
- restart Notepad and enable the theme
