### ISSUE TITLE
Special characters v7.3.2

### ISSUE THREAD

**Issue by szabosa** [naderi/material-theme-for-npp#8]
Special characters coloring (with Hungarian keyboard layout) is not working:

![image](https://user-images.githubusercontent.com/41210156/45737294-ab46fe80-bbed-11e8-8aed-cb73552afca4.png)

What should I modify to use color styles on special characters too?

Thank you in advance.

**Comment by naderi** [comment]
I have no problem with German special characters!
![np++](https://user-images.githubusercontent.com/27568/60178141-0bbd3900-981b-11e9-94c1-4dc01f491a36.png)
